<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmpleadosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('empleados')->insert([
            
            // Gerente RRHH
            [
                'cedula' => 19708471,
                'nombre' => 'Gerente',
                'apellido' =>' RRHH',
                'nacionalidad' => 'v',
                'fecha_nacimiento' => '1990-10-01',
                'estado_civil' => 'solter@',
                'foto' => '',
                'sexo' => 'm',
                'estado'=> 'sucre',
                'ciudad' => 'cumana',
                'direccion' => 'Av Cancamure',
                'telefono_fijo' => '02945111580',
                'telefono_movil' => '04167834720',
                'email' =>'GerenteRRHH@hotmail.com',
                'tipo_discapacidad' => 'visual',
                'sucursal_id' => 1,
                'departamento_id' => 1,
                'cargo_id' => 31,
                'tipo_empleado' => 'administrativo',
                'nivel_academico' => 'profesional',
                'profesion' => 'Administración de Empresas',
                'condicion_laboral' => 'fijo',
                'tipo_horario' => 'fijo',
                'fecha_ingreso' => '2000-01-01',
                'banco' =>'banesco',
                'cuenta_bancaria'=> '01341234567891234546',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
                // area administrativa
            [
                'cedula' => 19708472,
                'nombre' => 'Renzo Jose',
                'apellido' =>' Rojas Quezada',
                'nacionalidad' => 'v',
                'fecha_nacimiento' => '1990-10-01',
                'estado_civil' => 'solter@',
                'foto' => '',
                'sexo' => 'm',
                'estado'=> 'sucre',
                'ciudad' => 'Rio caribe',
                'direccion' => 'Av Romulo Gallegos',
                'telefono_fijo' => '02945111580',
                'telefono_movil' => '04167834720',
                'email' =>'Analista-Administrativo@hotmail.com',
                'tipo_discapacidad' => 'visual',
                'sucursal_id' => 1,
                'departamento_id' => 1,
                'cargo_id' => 32,
                'tipo_empleado' => 'administrativo',
                'nivel_academico' => 'profesional',
                'profesion' => 'Administración de Empresas',
                'condicion_laboral' => 'fijo',
                'tipo_horario' => 'fijo',
                'fecha_ingreso' => '2000-01-01',
                'banco' =>'banesco',
                'cuenta_bancaria'=> '01341234567891234568',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],

                        // area operativa
            [
                'cedula' => 19708473,
                'nombre' => 'Cesar',
                'apellido' =>' Fabbianni',
                'nacionalidad' => 'v',
                'fecha_nacimiento' => '1980-10-01',
                'estado_civil' => 'solter@',
                'foto' => '',
                'sexo' => 'm',
                'estado'=> 'sucre',
                'ciudad' => 'cumana',
                'direccion' => 'Av Bolivar',
                'telefono_fijo' => '02945111580',
                'telefono_movil' => '04167834720',
                'email' =>'Analista-Operativo@hotmail.com',
                'tipo_discapacidad' => 'visual',
                'sucursal_id' => 1,
                'departamento_id' => 1,
                'cargo_id' => 33,
                'tipo_empleado' => 'administrativo',
                'nivel_academico' => 'profesional',
                'profesion' => 'Administración Pública',
                'condicion_laboral' => 'fijo',
                'tipo_horario' => 'fijo',
                'fecha_ingreso' => '2000-01-01',
                'banco' =>'banesco',
                'cuenta_bancaria'=> '01341234567891234569',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],

                    // area telematica
            [
                'cedula' => 19708474,
                'nombre' => 'Victor',
                'apellido' =>'Guzman',
                'nacionalidad' => 'v',
                'fecha_nacimiento' => '1980-10-01',
                'estado_civil' => 'solter@',
                'foto' => '',
                'sexo' => 'm',
                'estado'=> 'sucre',
                'ciudad' => 'cumana',
                'direccion' => 'La Casimba',
                'telefono_fijo' => '02945111580',
                'telefono_movil' => '04167834720',
                'email' =>'Analista-telematico@hotmail.com',
                'tipo_discapacidad' => 'visual',
                'sucursal_id' => 1,
                'departamento_id' => 1,
                'cargo_id' => 34,
                'tipo_empleado' => 'administrativo',
                'nivel_academico' => 'profesional',
                'profesion' => 'Telecomunicaciones',
                'condicion_laboral' => 'fijo',
                'tipo_horario' => 'fijo',
                'fecha_ingreso' => '2000-01-01',
                'banco' =>'banesco',
                'cuenta_bancaria'=> '01341234567891234560',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],

                // area apoyo logistico
            [
                'cedula' => 19708475,
                'nombre' => 'Carolina',
                'apellido' =>' Carvajal',
                'nacionalidad' => 'v',
                'fecha_nacimiento' => '1980-10-01',
                'estado_civil' => 'solter@',
                'foto' => '',
                'sexo' => 'f',
                'estado'=> 'sucre',
                'ciudad' => 'cumana',
                'direccion' => 'Av cumanacoa km 8',
                'telefono_fijo' => '02945111580',
                'telefono_movil' => '04167834720',
                'email' =>'Analista-Apoyo-Logistico@hotmail.com',
                'tipo_discapacidad' => 'visual',
                'sucursal_id' => 1,
                'departamento_id' => 1,
                'cargo_id' => 35,
                'tipo_empleado' => 'administrativo',
                'nivel_academico' => 'profesional',
                'profesion' => 'Ingeniería Logística',
                'condicion_laboral' => 'fijo',
                'tipo_horario' => 'fijo',
                'fecha_ingreso' => '2000-01-01',
                'banco' =>'banesco',
                'cuenta_bancaria'=> '01341234567891234561',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],

                            // area oficina
            [
                'cedula' => 19708476,
                'nombre' => 'Isabel',
                'apellido' =>'lopez',
                'nacionalidad' => 'v',
                'fecha_nacimiento' => '1980-10-01',
                'estado_civil' => 'solter@',
                'foto' => '',
                'sexo' => 'f',
                'estado'=> 'sucre',
                'ciudad' => 'cumana',
                'direccion' => 'Urb. San Miguel',
                'telefono_fijo' => '02945111580',
                'telefono_movil' => '04167834720',
                'email' =>'Analista-oficina@hotmail.com',
                'tipo_discapacidad' => 'visual',
                'sucursal_id' => 1,
                'departamento_id' => 1,
                'cargo_id' => 36,
                'tipo_empleado' => 'administrativo',
                'nivel_academico' => 'profesional',
                'profesion' => 'Economía',
                'condicion_laboral' => 'fijo',
                'tipo_horario' => 'fijo',
                'fecha_ingreso' => '2000-01-01',
                'banco' =>'banesco',
                'cuenta_bancaria'=> '01341234567891234562',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],

                             // area tripulacion
            [
                'cedula' => 19708477,
                'nombre' => 'Luis',
                'apellido' =>'Gutierres',
                'nacionalidad' => 'v',
                'fecha_nacimiento' => '1980-10-01',
                'estado_civil' => 'solter@',
                'foto' => '',
                'sexo' => 'm',
                'estado'=> 'sucre',
                'ciudad' => 'cumana',
                'direccion' => 'Super Bloques',
                'telefono_fijo' => '02945111580',
                'telefono_movil' => '04167834720',
                'email' =>'Analista-Tripulacion@hotmail.com',
                'tipo_discapacidad' => 'visual',
                'sucursal_id' => 1,
                'departamento_id' => 1,
                'cargo_id' => 37,
                'tipo_empleado' => 'administrativo',
                'nivel_academico' => 'profesional',
                'profesion' => 'Ingeniería Aeronáutica',
                'condicion_laboral' => 'fijo',
                'tipo_horario' => 'fijo',
                'fecha_ingreso' => '2000-01-01',
                'banco' =>'banesco',
                'cuenta_bancaria'=> '01341234567891234563',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],

                // Gerente Sucursales
           [
                'cedula' => 19708478,
                'nombre' => 'Gerente',
                'apellido' =>'Sucursal',
               'nacionalidad' => 'v',
                'fecha_nacimiento' => '1980-10-01',
                'estado_civil' => 'solter@',
                'foto' => '',
                'sexo' => 'm',
                'estado'=> 'sucre',
                'ciudad' => 'cumana',
                'direccion' => 'El Peñon',
                'telefono_fijo' => '02945111580',
                'telefono_movil' => '04167834720',
                'email' =>'Gerente-Sucursal@hotm1il.com',
                'tipo_discapacidad' => 'visual',
                'sucursal_id' => 1,
                'departamento_id' => 1,
                'cargo_id' => 38,
                'tipo_empleado' => 'administrativo',
                'nivel_academico' => 'profesional',
                'profesion' => 'Negocios Internacionales',
                'condicion_laboral' => 'fijo',
                'tipo_horario' => 'fijo',
                'fecha_ingreso' => '2000-01-01',
                'banco' =>'banesco',
                'cuenta_bancaria'=> '01341234567891234564',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],

            // Analista Nomina
            [
                'cedula' => 19708479,
                'nombre' => 'Analista',
                'apellido' =>'Nomina',
                'nacionalidad' => 'v',
                'fecha_nacimiento' => '1980-10-01',
                'estado_civil' => 'solter@',
                'foto' => '',
                'sexo' => 'm',
                'estado'=> 'sucre',
                'ciudad' => 'cumana',
                'direccion' => 'El Centro',
                'telefono_fijo' => '02945111580',
                'telefono_movil' => '04167834720',
                'email' =>'Analista-Nomina@hotmail.com',
                'tipo_discapacidad' => 'visual',
                'sucursal_id' => 1,
                'departamento_id' => 1,
                'cargo_id' => 39,
                'tipo_empleado' => 'administrativo',
                'nivel_academico' => 'profesional',
                'profesion' => 'Contaduría Pública',
                'condicion_laboral' => 'fijo',
                'tipo_horario' => 'fijo',
                'fecha_ingreso' => '2000-01-01',
                'banco' =>'banesco',
                'cuenta_bancaria'=> '01341234567891234565',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],

        ]);
    }
}
